### ISSUE TITLE
is this supports imgur api and youtube api

### ISSUE THREAD

**Issue by santoshgistto** [chevereto/v2#1]

**Comment by rodber** [comment]
Can you be more specific?

**Comment by santoshgistto** [comment]
@rodolfoberrios  i would like to add only image urls that may contain image/gif/video(youtube) url 

sorry may be this is irrelevant question here

**Comment by rodber** [comment]
"Chevereto 2.X" is actually discontinued from the main script which is Chevereto so all additions and new stuff goes there: https://chevereto.com/community/forums/requests-ideas-and-suggestions.1/

Since this issue has nothing to do with the actual code here I will close this one now.
